# Generated by Django 3.1.7 on 2021-05-31 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20210531_1641'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can mark returned', 'Set book as returned'),)},
        ),
    ]
